version: '3.9'

services:
  bot:
    build: .
    container_name: project_assistant_bot
    volumes:
      - ./logs:/app/logs
      - ./bot/users.db:/app/bot/users.db
      - ./docs:/app/docs
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=vector_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=vector
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - bot_network

  postgres:
    image: pgvector/pgvector:pg16
    container_name: project_assistant_postgres
    environment:
      - POSTGRES_DB=vector_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=vector
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - bot_network

volumes:
  postgres_data:

networks:
  bot_network:
    driver: bridge 